POST http://localhost:3001/api/events/
Content-Type: application/json

{
    "type": "event",
    "description": "hello there",
    "date": "2018-06-01",
    "title": "Points not actually",
    "points": null
}
